#!/bin/bash

# To connect to wifi:
#	wifi-menu or nmtui
# To install big font:
# 	pacman -Sy terminus-font
# 	setfont ter-p32n
set -eo pipefail
trap quit:no_message INT

command -v dialog >/dev/null 2>&1 || pacman -Sy --noconfirm --needed dialog

INSTALL_SCRIPT=install_arch.sh
EDITOR=vim
hostname=$(dialog --stdout --inputbox "Enter hostname" 0 0) || exit 1
username=$(dialog --stdout --inputbox "Enter username" 0 0) || exit 1
password=$(dialog --stdout --passwordbox "Enter password" 0 0) || exit 1
password2=$(dialog --stdout --passwordbox "Confirm password" 0 0) || exit 1
[[ "$password" == "$password2" ]] || ( echo "Passwords did not match"; exit 1; )
dotfiles=$(dialog --stdout --inputbox "dotfiles repo (ex: prabirshrestha/dotfiles)" 0 0) || exit 1

devicelist=$(lsblk -dplnx size -o name,size | grep -Ev "boot|rpmb|loop" | tac)
device=$(dialog --stdout --menu "Select installation disk" 0 0 0 ${devicelist}) || exit 1
device_root="${device}1"
device_boot="${device}2"

write_script() {
	(
		echo "#!/usr/bin/env bash"
		echo "#"
		echo "# Please review the install script below"
		echo "#"
		echo "set -euo pipefail"
		echo
		echo "sgdisk -Z $device"
		echo "sgdisk -Z $device"
		echo "sgdisk -z $device"
		echo "sgdisk -o $device"
		echo
		echo "sgdisk -n 1:0:-200M $device"
		echo "sgdisk -t 1:8300 $device"
		echo
		echo "sgdisk -n 2:-200M:-0 $device"
		echo "sgdisk -t 2:ef00 $device"
		echo "sgdisk -A 2:set:2 $device"
		echo
		echo "mkfs.btrfs -f $device_root"
		echo "mkfs.fat -F32 $device_boot"
		echo
		echo "mount $device_root /mnt"
		echo "mkdir -p /mnt/boot/efi"
		echo "mount $device_boot /mnt/boot/efi"
		echo
		echo "echo \"Server = http://mirrors.ocf.berkeley.edu/archlinux/\\\$repo/os/\\\$arch\" >> /etc/pacman.d/mirrorlist"
		echo
		echo "pacstrap /mnt base base-devel linux linux-firmware grub efibootmgr networkmanager sudo vim"
		echo
		echo "genfstab -U -p /mnt > /mnt/etc/fstab"
		echo
		echo "ln -sf /mnt/usr/share/zoneinfo/America/Los_Angeles /mnt/etc/localtime"
		echo
		echo "echo "LANG=en_US.UTF-8" > /mnt/etc/locale.conf"
		echo "sed -i 's/#en_US.UTF/en_US.UTF/' /mnt/etc/locale.gen"
		echo "arch-chroot /mnt locale-gen"
		echo
		echo "arch-chroot /mnt sh <<EOF"
		echo "	echo ${hostname} > /etc/hostname"
		echo "EOF"
		echo "arch-chroot /mnt systemctl enable NetworkManager.service"
		echo
		echo "arch-chroot /mnt grub-install --target=x86_64-efi --bootloader-id=grub --efi-directory=/boot/efi --recheck"
		echo "arch-chroot /mnt grub-mkconfig -o /boot/grub/grub.cfg"
		echo "mkdir -p /mnt/boot/efi/EFI/BOOT"
		echo "cp /mnt/boot/efi/EFI/GRUB/grubx64.efi /mnt/boot/efi/EFI/BOOTX64.EFI"
		echo
		echo "# setup sudo"
		echo "arch-chroot /mnt sh <<EOF"
		echo "	echo '%wheel ALL=(ALL) ALL' | sudo EDITOR='tee -a' visudo"
		echo "EOF"
		echo
		echo "# create user"
		echo "arch-chroot /mnt sh <<EOF"
		echo "	useradd -Nm -g users -G wheel,sys \"$username\""
		echo "  passwd -d \"$username\""
		echo "EOF"
		echo
		echo "# install paru-bin"
		echo "arch-chroot /mnt bash <<EOF"
		echo "  cd /tmp"
		echo "  curl -O https://aur.archlinux.org/cgit/aur.git/snapshot/paru-bin.tar.gz"
		echo "  tar -xvf paru-bin.tar.gz"
		echo "  chmod 777 paru-bin"
		echo "  cd paru-bin"
		echo "  su $username"
		echo "  makepkg -sirc --noconfirm"
		echo "  cd .."
		echo "EOF"
		echo
		echo "arch-chroot /mnt sudo -u $username paru --noconfirm -S wezterm-bin nerd-fonts-fira-code lua z.lua"
		echo
		echo "# install gui"
		echo "arch-chroot /mnt bash <<EOF"
		echo "  pacman -S --noconfirm xf86-video-intel"
		echo "  #pacman -S --noconfirm xf86-video-nouveau"
		echo
		echo "  pacman -S --noconfirm xorg-server xorg-xinit xterm xorg-xbacklight alsa-utils ttf-fira-code ttf-freefont ttf-arphic-uming ttf-baekmuk pulseaudio"
		echo
		echo "  pacman -S --noconfirm sddm; systemctl enable sddm.service"
        echo "  # acpid for battery status"
		echo "  pacman -S --noconfirm acpi acpid; systemctl enable acpid"
		echo
		echo "  #su $username -c 'paru -S --noconfirm dwm-git'"
		echo "  pacman -S --noconfirm awesome nemo rofi arc-icon-theme"
		echo "  #pacman -S --noconfirm bspwm sxhkd wmctrl xorg-xprop xorg-xsetroot"
		echo "  #su $username -c 'paru -S --noconfirm lemonbar-git'"
		echo "  #pacman -S --noconfirm gnome gdm gnome-tweak-tool; systemctl enable gdm"
		echo "  #pacman -S --noconfirm xfce4"
		echo "  #pacman -S --noconfirm plasma konsole"
		echo
		echo "  pacman -S --noconfirm firefox-developer-edition"
		echo
		echo "  #xbacklight -set 100"
		echo "EOF"
		echo
		echo "arch-chroot /mnt sh <<EOF"
		echo "  pacman -S --noconfirm fuse"
		echo "EOF"
		echo
		echo "# dev"
		echo "arch-chroot /mnt sh <<EOF"
		echo "  pacman -S --noconfirm gvim git openssh tmux unzip wget ripgrep fzf man flameshot libz3"
		echo "  pacman -S --noconfirm virtualbox"
		echo "  pacman -S --noconfirm rust cargo-edit cargo-outdated cargo-watch"
		echo "  pacman -S --noconfirm docker; usermod -aG docker $username; systemctl enable docker.service"
		echo "EOF"
		echo
		echo "arch-chroot /mnt bash <<EOF"
		echo "  pacman -Syu --noconfirm --needed git"
		echo "  cd /home/$username"
		echo "  curl -Lk https://github.com/ubnt-intrepid/dot/releases/download/v0.1.4/dot-v0.1.4-x86_64-unknown-linux-musl.tar.gz -o dot.tar.gz"
		echo "  tar -xvf ./dot.tar.gz"
		echo "  rm ./dot.tar.gz"
		echo "  mv ./dot /bin/"
		echo "  su $username -c 'dot init $dotfiles'"
		echo "EOF"
		echo
		echo "# create user password"
		echo "arch-chroot /mnt sh <<EOF"
		echo "	echo -e "$password"\"\\n\"$password | passwd \"$username\""
		echo "EOF"
		echo
		echo "# disallow root login"
		echo "arch-chroot /mnt passwd -l root"
	) > "$INSTALL_SCRIPT"
	chmod +x "$INSTALL_SCRIPT"
}

write_script

# open editor to review and make last changes to the script
"$EDITOR" "$INSTALL_SCRIPT"
reset

clear

dialog --title "Arch Installer" --yesno "Are you sure you want to run the script?" 7 60
response=$?
clear

case $response in
	0) bash "$INSTALL_SCRIPT";;
	1) clear && echo "Cancelling installation";;
	255) clear && echo "Cancelling installation";;
esac
